Repository rachelchrisjeremy/web-app, pull requests merged in 2018-02, with the labels that each got.

#27 add basic headings
  index.html
Labels: bug, dev

#28 Buttons and Nav
  common/grid.css
  common/modules.css
  common/theme.css
  common/type.css
  common/typekit.js
  patterns/buttons/README.md
  patterns/buttons/buttons.css
  patterns/buttons/buttons.html
  patterns/footer/README.md
  patterns/footer/css/main.css
  patterns/footer/index.html
  patterns/navigation/README.md
  patterns/navigation/css/main.css
  patterns/navigation/index.html
Labels: dev

#29 Icons code
  icons.html
Labels: bug, dev

#30 Icons
  images/icons.svg
Labels: bug, dev

#31 added cards
  common/typekit.js
  images/placeholder-16by9.svg
  images/placeholder-1by1.svg
  images/placeholder-circle.svg
  patterns/cards/cards.css
  patterns/cards/cards.html
  patterns/icons/icons.html
Labels: bug, dev

#37 updating
  index.html
  patterns/icons/icons.html
Labels: bug, dev

#38 changes
  common/theme.css
  patterns/cards/cards.css
  patterns/cards/cards.html
  patterns/icons/icons.html
Labels: bug

#39 added correct colour
  common/theme.css
Labels: dev
